name: Docker Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./app/requirements.txt
        # Install any testing framework you are using (e.g., pytest)
        pip install pytest

    - name: Test with pytest
      run: pytest tests.py --doctest-modules --junitxml=junit/test-results.xml
      
    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      with:
          name: pytest-results
          path: junit/test-results.xml
        # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}

    - name: Build the Docker image
      run: docker build -t my-flask-app ./app/
      # Replace 'my-flask-app' with your desired image name