name: Docker Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./app/requirements.txt
        # Install any testing framework you are using (e.g., pytest)
        pip install pytest

    - name: Run tests
      run: |
        # Replace this with the command to run your tests
        # For example, if your tests are in a 'tests' directory and you use pytest:
        pytest tests/
        # If you have a specific test command, use that instead
        # For example, for unittest discovery:
        # python -m unittest discover -p 'test_*.py'
        echo "Remember to configure your test execution command!"

    - name: Build the Docker image
      run: docker build -t my-flask-app .
      # Replace 'my-flask-app' with your desired image name